version: '3.8'
services:
  ntp-server:
    build: ./docker
    container_name: ntp-server
    restart: unless-stopped
    network_mode: bridge  # Default network mode
    ports:
      - "123:123/udp"  # Expose NTP service on UDP port 123
    volumes:
      - ./docker/ntp.conf:/etc/ntp.conf  # Mount custom NTP configuration